# Generated by Django 2.2.1 on 2019-05-19 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.IntegerField(choices=[(1, 'Ativo'), (2, 'Inativo'), (3, 'Deletado')], default=1, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'day',
                'verbose_name_plural': 'days',
                'db_table': 'days',
            },
        ),
        migrations.CreateModel(
            name='CourseDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.CharField(max_length=20)),
                ('course', models.ManyToManyField(related_name='date_course', to='courses.Course')),
                ('days', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_course', to='courses.Day')),
            ],
            options={
                'verbose_name': 'coursedate',
                'verbose_name_plural': 'coursedates',
                'db_table': 'coursedates',
            },
        ),
    ]
