# Generated by Django 2.2.1 on 2019-05-19 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursedate',
            name='days',
        ),
        migrations.AddField(
            model_name='coursedate',
            name='day',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='course',
            table='Courses',
        ),
        migrations.AlterModelTable(
            name='coursedate',
            table='CourseDates',
        ),
        migrations.DeleteModel(
            name='Day',
        ),
    ]
