# Generated by Django 2.2.1 on 2019-05-19 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20190519_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursedate',
            name='course',
        ),
        migrations.AddField(
            model_name='coursedate',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='date_course', to='courses.Course'),
            preserve_default=False,
        ),
    ]
