# Generated by Django 2.2.1 on 2019-05-22 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20190519_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursedate',
            name='course',
        ),
        migrations.AddField(
            model_name='coursedate',
            name='course',
            field=models.ManyToManyField(related_name='date_course', to='courses.Course'),
        ),
    ]
