# Generated by Django 2.2.5 on 2019-10-18 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20190521_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='date_course',
        ),
        migrations.AlterModelTable(
            name='course',
            table='courses',
        ),
        migrations.DeleteModel(
            name='CourseDate',
        ),
    ]
