# Generated by Django 2.2.1 on 2019-05-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20190519_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.IntegerField(choices=[(1, 'Adimplente'), (2, 'Inadimplente'), (3, 'Deletado')], default=1, verbose_name='Status'),
        ),
    ]
