# Generated by Django 2.2.1 on 2019-05-19 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0003_auto_20190519_1635'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(1, 'Ativo'), (2, 'Inativo'), (3, 'Deletado')], default=1, verbose_name='Status')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_course', to='courses.Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_student', to='student.Student')),
            ],
            options={
                'verbose_name': 'class',
                'verbose_name_plural': 'classrooms',
                'db_table': 'classrooms',
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.TextField(blank=True, max_length=1000)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observation_class', to='class.Class')),
            ],
            options={
                'verbose_name': 'observation',
                'verbose_name_plural': 'observations',
                'db_table': 'observations',
            },
        ),
    ]
