# Generated by Django 2.2.1 on 2019-05-19 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_auto_20190519_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtGenerate', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(1, 'Gerado'), (2, 'Não Gerado'), (3, 'Deletado')], default=1, verbose_name='Status')),
                ('finance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_finance', to='finances.Finance')),
            ],
        ),
    ]
