# Generated by Django 2.2.5 on 2019-10-18 18:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('roomclass', '0002_auto_20190530_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomclass',
            name='date',
        ),
        migrations.AddField(
            model_name='roomclass',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de criação'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='observation',
            name='observation',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AlterModelTable(
            name='observation',
            table='observation_classes',
        ),
        migrations.AlterModelTable(
            name='roomclass',
            table='classes',
        ),
    ]
